In [41]:
import numpy as np

In [42]:
from numpy import genfromtxt
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')

In [43]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [44]:
labels = data[:,4]

In [45]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [46]:
features = data[:,0:4]

In [47]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [48]:
X = features
y = labels

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [51]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [52]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [53]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [54]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [55]:
from sklearn.preprocessing import MinMaxScaler

In [56]:
scaler_object = MinMaxScaler()

In [57]:
scaler_object.fit(X_train)

MinMaxScaler()

In [58]:
scaled_X_train = scaler_object.transform(X_train)

In [59]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [60]:
X_train.max()

17.9274

In [61]:
scaled_X_train.max()

1.0000000000000002

In [62]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [63]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [64]:
from keras.models import Sequential
from keras.layers import Dense

In [65]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(4, input_dim=4, activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

C:\Users\mjink\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Compile Model

In [66]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit (Train) the Model

In [67]:
# Play around with number of epochs as well!
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - 46ms/step - accuracy: 0.5626 - loss: 0.6899
Epoch 2/50
29/29 - 0s - 2ms/step - accuracy: 0.5604 - loss: 0.6870
Epoch 3/50
29/29 - 0s - 2ms/step - accuracy: 0.5473 - loss: 0.6840
Epoch 4/50
29/29 - 0s - 2ms/step - accuracy: 0.5506 - loss: 0.6801
Epoch 5/50
29/29 - 0s - 2ms/step - accuracy: 0.5582 - loss: 0.6742
Epoch 6/50
29/29 - 0s - 2ms/step - accuracy: 0.5767 - loss: 0.6663
Epoch 7/50
29/29 - 0s - 2ms/step - accuracy: 0.6039 - loss: 0.6535
Epoch 8/50
29/29 - 0s - 2ms/step - accuracy: 0.6899 - loss: 0.6269
Epoch 9/50
29/29 - 0s - 2ms/step - accuracy: 0.7486 - loss: 0.5910
Epoch 10/50
29/29 - 0s - 2ms/step - accuracy: 0.7454 - loss: 0.5644
Epoch 11/50
29/29 - 0s - 2ms/step - accuracy: 0.7541 - loss: 0.5408
Epoch 12/50
29/29 - 0s - 2ms/step - accuracy: 0.7584 - loss: 0.5198
Epoch 13/50
29/29 - 0s - 2ms/step - accuracy: 0.7748 - loss: 0.5012
Epoch 14/50
29/29 - 0s - 2ms/step - accuracy: 0.7802 - loss: 0.4862
Epoch 15/50
29/29 - 0s - 2ms/step - accuracy: 0.7922 - l

In [68]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [71]:
# Spits out probabilities by default.
model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([[0.05318063],
       [0.48490217],
       [0.2910472 ],
       [0.09637972],
       [0.04725818],
       [0.01796104],
       [0.22110234],
       [0.01359111],
       [0.03329433],
       [0.14147148],
       [0.51668835],
       [0.8875125 ],
       [0.17180079],
       [0.8224882 ],
       [0.66355467],
       [0.2598594 ],
       [0.9281805 ],
       [0.93621016],
       [0.89894086],
       [0.86762667],
       [0.02699522],
       [0.07727506],
       [0.8802052 ],
       [0.02081245],
       [0.9956736 ],
       [0.01937608],
       [0.01569154],
       [0.8754159 ],
       [0.01433938],
       [0.01047504],
       [0.75798005],
       [0.10612629],
       [0.16070649],
       [0.9967705 ],
       [0.986698  ],
       [0.01626095],
       [0.4855428 ],
       [0.8076514 ],
       [0.9032469 ],
       [0.09165847],
       [0.05453921],
       [0.7570424 ],
       [0.82175857],
       [0.03135227],
       [0.9865308 ],
       [0.87719464],
       [0.95832306],
       [0.027

In [72]:
model.predict_classes(scaled_X_test)

AttributeError: 'Sequential' object has no attribute 'predict_classes'