In [4]:
import numpy as np
from numpy import genfromtxt

In [5]:
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')

In [6]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [7]:
labels = data[:,4]

In [8]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [9]:
features = data[:,0:4]

In [10]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X = features
y = labels

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [15]:
len(X_train)

919

In [18]:
len(X_test)

453

In [16]:
len(X)

1372

In [19]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [ ]:
y_train

In [ ]:
y_test

In [24]:
X_test.max()

17.1116

In [23]:
X_test.min()

-13.2869

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler_object = MinMaxScaler()

In [26]:
scaler_object.fit(X_train)

MinMaxScaler()

In [27]:
scaled_X_train = scaler_object.transform(X_train)

In [28]:
scaled_X_test = scaler_object.transform(X_test)

In [29]:
X_train.max()

17.9274

In [30]:
scaled_X_train.max()

1.0000000000000002

In [31]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [32]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [33]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
# Creates model
model = Sequential()

# 8 Neurons, expects input of 4 features.
model.add(Dense(4, input_dim=4, activation='relu'))

# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
model.add(Dense(8, activation='relu'))

# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))

C:\Users\mjink\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Compile Model

In [35]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit (Train) the Model

In [37]:
model.fit(scaled_X_train,y_train,epochs=50, verbose=2)

Epoch 1/50
29/29 - 0s - 4ms/step - accuracy: 0.9478 - loss: 0.1811
Epoch 2/50
29/29 - 0s - 4ms/step - accuracy: 0.9478 - loss: 0.1769
Epoch 3/50
29/29 - 0s - 4ms/step - accuracy: 0.9499 - loss: 0.1721
Epoch 4/50
29/29 - 0s - 4ms/step - accuracy: 0.9499 - loss: 0.1681
Epoch 5/50
29/29 - 0s - 5ms/step - accuracy: 0.9510 - loss: 0.1643
Epoch 6/50
29/29 - 0s - 5ms/step - accuracy: 0.9499 - loss: 0.1609
Epoch 7/50
29/29 - 0s - 5ms/step - accuracy: 0.9554 - loss: 0.1576
Epoch 8/50
29/29 - 0s - 5ms/step - accuracy: 0.9510 - loss: 0.1510
Epoch 9/50
29/29 - 0s - 5ms/step - accuracy: 0.9554 - loss: 0.1460
Epoch 10/50
29/29 - 0s - 6ms/step - accuracy: 0.9543 - loss: 0.1411
Epoch 11/50
29/29 - 0s - 5ms/step - accuracy: 0.9543 - loss: 0.1365
Epoch 12/50
29/29 - 0s - 5ms/step - accuracy: 0.9543 - loss: 0.1318
Epoch 13/50
29/29 - 0s - 5ms/step - accuracy: 0.9576 - loss: 0.1274
Epoch 14/50
29/29 - 0s - 5ms/step - accuracy: 0.9576 - loss: 0.1234
Epoch 15/50
29/29 - 0s - 5ms/step - accuracy: 0.9587 - lo

In [38]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [39]:
# Get the predicted probabilities
probabilities = model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step


In [40]:
# Convert probabilities to class labels
predicted_classes = (probabilities > 0.5).astype("int32")

In [144]:
model.metrics_names

['loss', 'compile_metrics']

In [145]:
model.evaluate(x=scaled_X_test,y=y_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9755 - loss: 0.1016  


[0.08799552172422409, 0.9801324605941772]

In [146]:
from sklearn.metrics import confusion_matrix,classification_report

In [147]:
# Get predicted probabilities
probabilities = model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [148]:
# Convert probabilities to class labels
predicted_classes = (probabilities > 0.5).astype("int32")

In [149]:
confusion_matrix(y_test,predicted_classes)

array([[254,   3],
       [  6, 190]], dtype=int64)

In [150]:
print(classification_report(y_test,predicted_classes))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98       257
         1.0       0.98      0.97      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



In [155]:
model.save('myfirstmodel.keras')

In [156]:
from keras.models import load_model
newmodel = load_model('myfirstmodel.keras')

C:\Users\mjink\AppData\Roaming\Python\Python311\site-packages\keras\src\saving\saving_lib.py:713: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [157]:
import numpy as np
predictions = newmodel.predict(X_test)
class_predictions = np.argmax(predictions, axis=1)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
